#!/usr/bin/env python

env = SConscript("godot-cpp/SConstruct")

env.Append(CPPPATH=[
    "src/include",
    "src/private",
    "src"
])

sources = []
sources += Glob("src/*.cpp")
sources += Glob("src/private/*.cpp")

folder = "addons/GDExtAbilities/bin"

if env["platform"] == "macos":
	file_name = "libGDExtAbilities.{}.{}".format(env["platform"], env["target"])

	library = env.SharedLibrary(
		"{}/{}.framework/{}".format(folder, file_name, file_name),
		source=sources
	)
else:
	library = env.SharedLibrary(
		"{}/libGDExtAbilities{}{}"
			.format(folder, env["suffix"], env["SHLIBSUFFIX"]),
		source=sources,
	)

CacheDir(".scons_cache/")

Default(library)