#!/usr/bin/env python

import os

env = SConscript("godot-cpp/SConstruct")

# ---------------------------------------------------
if "CXXFLAGS" in env:
    env["CXXFLAGS"] = [flag for flag in env["CXXFLAGS"] if flag != "/std:c++17"]

env.Append(CXXFLAGS=[
    "/std:c++20",
    "/EHsc"
])

# ---------------------------------------------------
env.Append(CPPPATH=[
    "src/include",
    "src/private",
    "src",
    "godot-cpp/gen/include/",
])

# ---------------------------------------------------
build_dir = f"build/{env['platform']}/{env['target']}"
src_dir = "src"

env.VariantDir(build_dir, src_dir, duplicate=0)

doc_sources = []
if env["target"] in ["editor", "template_debug"]:
    try:
        doc_data = env.GodotCPPDocData(
            f"{build_dir}/gen/doc_data.gen.cpp", 
            source=Glob("../demos/demo0/doc_classes/*.xml")
        )
        doc_sources.append(doc_data)
        print("--- Generating documentation XML ---")
    except AttributeError:
        print("Not including class reference as we're targeting a pre-4.3 baseline.")

if env["target"] == "editor":
    env.Append(CPPDEFINES=["TOOLS_ENABLED"])

# ---------------------------------------------------
sources = []
for root, dirs, files in os.walk(src_dir):
    for file in files:
        if file.endswith(".cpp"):
            rel_path = os.path.relpath(os.path.join(root, file), src_dir)
            sources.append(os.path.join(build_dir, rel_path))

sources.extend(doc_sources)

# ---------------------------------------------------
folder = "addons/GDExtAbilities/bin"

if env["platform"] == "macos":
    file_name = f"libGDExtAbilities.{env['platform']}.{env['target']}"

    library = env.SharedLibrary(
        f"{folder}/{file_name}.framework/{file_name}",
        source=sources
    )
else:
    library = env.SharedLibrary(
        f"{folder}/libGDExtAbilities{env['suffix']}{env['SHLIBSUFFIX']}",
        source=sources
    )

# ---------------------------------------------------
CacheDir(".scons_cache/")
Default(library)